name: Push Search Data to Algolia

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [ publish-event ]

jobs:
  update-algolia-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install algoliasearch@4

      - name: Run Algolia Indexing Script
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: node scripts/index-to-algolia.js